// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselHeightController from "./carousel_height_controller"
application.register("carousel-height", CarouselHeightController)

import CollapseController from "./collapse_controller"
application.register("collapse", CollapseController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import GuestsController from "./guests_controller"
application.register("guests", GuestsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageGalleryController from "./image_gallery_controller"
application.register("image-gallery", ImageGalleryController)

import LoadMoreController from "./load_more_controller"
application.register("load-more", LoadMoreController)

import MapController from "./map_controller"
application.register("map", MapController)
